### ISSUE TITLE
An error when compile

### ISSUE THREAD

**Issue by ralph-nj** [rieck/harry#21]
./configure --prefix=/opt/harry  --with-libarchive
make
error message
make[3]: Entering directory `/home/harry-0.4.0/src'
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2 -DNDEBUG -std=c99 -fgnu89-inline -Wall -fPIC   -fopenmp    -o harry harry.o libharry.la -lpthread -larchive -lz  -lm -lconfig
libtool: link: gcc -g -O2 -DNDEBUG -std=c99 -fgnu89-inline -Wall -fPIC -fopenmp -o harry harry.o  ./.libs/libharry.a -lpthread -larchive -lz -lm -lconfig -fopenmp
./.libs/libharry.a(input_arc.o): In function `input_arc_open':
/home/harry-0.4.0/src/input/input_arc.c:50: undefined reference to `archive_read_support_filter_all'
collect2: ld returned 1 exit status
make[3]: *** [harry] Error 1
make[3]: Leaving directory `/home/harry-0.4.0/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/harry-0.4.0/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/harry-0.4.0'
make: *** [all] Error 2

I have check the tools version of libarchive.
It's libarchive-devel-2.8.3-4.el6_2.x86_64
My system version is CentOS release 6.5

Please help me to fix this issue 
Thanks!

**Comment by rieck** [comment]
Please check whether a newer version of libarchive works, e.g. 3.1.2.
Konrad
