### ISSUE TITLE
problem building Harry 0.4.1 with "undefined reference to 'config_init'" error

### ISSUE THREAD

**Issue by hseuming** [rieck/harry#22]
Hi,
This is the first time that i tried to build Harry (with latest version 0.4.1).  However, i ran into some front-end compilation errors while firing off "make" (the ./configure appeared to go well) such as
    .../src/harry.c:357:  undefined reference to 'config_init'
    .../src/harry.c:360:  undefined reference to 'config_read_file'
    ....

All the errors reported are related to missing config_\* references (looks like for the C API).   i'm using libconfig_1.5 that i recently built.     Any idea what went astray?

Thanks for reading.

**Comment by rieck** [comment]
That's a very odd warning. Are you sure that `configure` finds your libconfig installation?
