### ISSUE TITLE
Were the Jellyfish benchmarks using the C or Python implementation?

### ISSUE THREAD

**Issue by nchammas** [rieck/harry#23]
Looking at [this paper here](http://jmlr.org/papers/volume17/rieck16a/rieck16a.pdf) I'm curious if the benchmarks against Jellyfish in section 3.2 were using the C or Python implementation. It's not clear from the paper.

**Comment by rieck** [comment]
We used a default installation of Jellyfish 0.5.0. It's a Python module. I am not sure if the module includes some C code, as for example python-Levenshtein. 

All benchmarks of Harry were computed using the "C version". The Python support of Harry is a simple wrapper that forwards the input to the binary and later on returns its output.

**Comment by nchammas** [comment]
Jellyfish does include [C implementations of all its algorithms](https://github.com/jamesturk/jellyfish/blob/c885531d3103e5c490d1ab50850554f5aac60964/setup.py#L75-L86), but I'm not sure how things were setup in 0.5.0. At least in the current version (0.5.6), Jellyfish will use the C implementations by default, with the Python implementations [available from a sub-module](https://github.com/jamesturk/jellyfish/blob/master/docs/index.rst#implementation).
